### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joeranbosma** [Yukiya-Umimi/ITUNet-for-PICAI-2022-Challenge#8]
Dear @Yukiya-Umimi,

Your repository currently does not contain a LICENSE file to indicate the license of the code in this repository. Could you add this, please? You can for example add the [Apache 2.0 License](https://github.com/DIAGNijmegen/picai_baseline/blob/main/LICENSE). For more information, see e.g. [here](https://choosealicense.com/) and [here](https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633).

Thanks!

**Comment by joeranbosma** [comment]
Thanks for adding the license!

**Comment by Yukiya-Umimi** [comment]
It's ok!



| |
Honey K
|




---- Replied Message ----
| From | Joeran ***@***.***> |
| Date | 03/09/2023 20:16 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Yukiya-Umimi/ITUNet-for-PICAI-2022-Challenge] License (Issue #8) |

Assigned #8 to @Yukiya-Umimi.
